channels:
  - conda-forge/label/jupyterlab_deck_alpha
  - conda-forge/label/jupyterlab_fonts_alpha
  - nodefaults
dependencies:
  - python >=3.11,<3.12
  - nodejs >=20,<21
  # talk
  - doit
  - importnb
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab >=4.0.7
  - jupyterlab-deck >=0.2.0a0
  # tools
  - asv
  - atheris
  - beartype
  - black
  - check-manifest
  - conda-lock
  - docformatter
  - firefox
  - geckodriver
  - hunspell-en
  - hypothesis
  - isort
  - jake
  - jupyter-lsp-python-plugins
  - jupyterlab-lsp
  - locust
  - monkeytype
  - mutpy
  - mypyc-ipython
  - pydocstyle
  - pyflakes
  - pyproject-fmt
  - pytest
  - pytest-check-links
  - pytest-cov
  - pytest-html
  - robotframework-jupyterlibrary >=0.5.0
  - ruff
  - schemathesis
  - snakeviz
  - ssort
  - taplo
  - tox
  - vale
  # semgrep deps
  - peewee
  - boltons
  - tqdm
  - parsy
  - face
  - click-option-group
  - bracex
  - wcmatch
  - glom
