channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.11
  - nodejs >=16,!=17.*,<19
  # talk
  - doit
  - importnb
  - ipydrawio
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab >=3.6
  - jupyterlab-deck
  - jupyterlab-myst
  # tools
  - asv
  - atheris
  - beartype
  - black
  - check-manifest
  - conda-lock
  - docformatter
  - firefox
  - geckodriver
  - hunspell-en
  - hypothesis
  - isort
  - jake
  - jupyter-lsp-python-plugins
  - jupyterlab-lsp
  - locust
  - monkeytype
  - mutpy
  - mypyc-ipython
  - pydocstyle
  - pyflakes
  - pytest
  - pytest-check-links
  - pytest-cov
  - robotframework-jupyterlibrary
  - schemathesis
  - snakeviz
  - ssort
  - tox
  # semgrep deps
  - peewee
  - boltons
  - tqdm
  - parsy
  - face
  - click-option-group
  - bracex
  - wcmatch
  - glom
