channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.11
  - nodejs =16
  # talk
  - doit
  - importnb
  - ipydrawio
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab >=3.5
  - jupyterlab-deck
  - jupyterlab-myst
  # tools
  - asv
  - atheris
  - beartype
  - black
  - check-manifest
  - conda-lock
  - conda-lock
  - docformatter
  - firefox
  - geckodriver
  - hunspell-en
  - hypothesis
  - isort
  - jake
  - jupyter-lsp-python-plugins
  - jupyterlab-lsp
  - locust
  - monkeytype
  - mutpy
  - mypyc-ipython
  - pydocstyle
  - pyflakes
  - pytest
  - pytest-check-links
  - pytest-cov
  - robotframework-jupyterlibrary
  - schemathesis
  - snakeviz
  - ssort
  - tox
  # pip deps
  - pip
  - pip:
    - semgrep
